# Generated by Django 5.0.6 on 2024-05-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_address_user_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
